# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'super_root.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image.super_root

class Ui_super_root(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(731, 642)
        Form.setMinimumSize(QtCore.QSize(731, 642))
        Form.setMaximumSize(QtCore.QSize(731, 642))
        icon = QtGui.QIcon.fromTheme("D:\\python_projects\\DataBase\\image\\logo.png")
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(0.85)
        Form.setStyleSheet("background-image: url(:/background/7.jpg);")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(220, 110, 271, 41))
        self.pushButton.setStyleSheet("font: 16pt \"Arial\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 190, 271, 41))
        self.pushButton_2.setStyleSheet("font: 16pt \"Arial\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 270, 271, 41))
        self.pushButton_3.setStyleSheet("font: 16pt \"Arial\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 350, 271, 41))
        self.pushButton_4.setStyleSheet("font: 16pt \"Arial\";")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "超级管理员"))
        self.pushButton.setText(_translate("Form", "查看小区信息"))
        self.pushButton_2.setText(_translate("Form", "查看楼栋信息"))
        self.pushButton_3.setText(_translate("Form", "增加新小区"))
        self.pushButton_4.setText(_translate("Form", "删除小区"))

